site_name: Schülerpraktikum bei Kia Deutschland IT
theme:
  name: material
plugins:
  - search:
      separator: '[\s\-\.]+'
      indexing: 'full'
      lang:
        - en
        - de
nav:
  - Einleitung: index.md
  - "Tag 1": day-01.md
  - "Tag 2": day-02.md
  - "Tag 3": day-03.md
  - "Tag 4": day-04.md
  - "Tag 5": day-05.md
  - "Tag 6": day-06.md
  - "Tag 7": day-07.md
  - "Tag 8": day-08.md
  - "Tag 9": day-09.md
  - "Tag 10": day-10.md

